### ISSUE TITLE
Error: Unable to parse EVENT_EVENT_TAG event from TPM log

### ISSUE THREAD

**Issue by lnussel** [okirch/pcr-oracle#49]
on real hardware:

```
# pcr-oracle --from eventlog --verify current predict 0,2,4,7,9 -d
::: Initializing predictor for sha256:0,2,4,7,9 from eventlog
::: Detected TPMv2 event log
::: Successfully read 36 events from TPM event log
::: Created new predictor
::: runtime_read_efi_application(/dev/sda2, /EFI/systemd/shim.efi)
::: Reading EFI application (/dev/sda2)/EFI/systemd/shim.efi
::: runtime_read_efi_application(/dev/sda2, /EFI/systemd/grub.efi)
::: Reading EFI application (/dev/sda2)/EFI/systemd/grub.efi
Error: Unable to parse EVENT_EVENT_TAG event from TPM log
::: 039fb: event type=EVENT_EVENT_TAG pcr=5 digests=2 data=32 bytes
:::   sha1       01d4e1ca16f118f6fcd954e175c0116c4a4f746b
:::   sha256     bdbea6dbc6791de89a483abc3a61af8e910249e7565682ff2011c910a490520a
:::   Data:
:::         0000  2a 58 bc f5 18 00 00 00 6c 00 6f 00 61 00 64 00 65 00 72 00 2e 00 63 00 6f 00 6e 00 66 00 00 00 *X......l.o.a.d.e.r...c.o.n.f...
Fatal: Aborting.
```

tpm2_eventlog works fine though. The event in question looks like this:

```
- EventNum: 32
  PCRIndex: 5
  EventType: EV_EVENT_TAG
  DigestCount: 2
  Digests:
  - AlgorithmId: sha1
    Digest: "01d4e1ca16f118f6fcd954e175c0116c4a4f746b"
  - AlgorithmId: sha256
    Digest: "bdbea6dbc6791de89a483abc3a61af8e910249e7565682ff2011c910a490520a"
  EventSize: 32
  Event: "2a58bcf5180000006c006f0061006400650072002e0063006f006e0066000000"
```
